### ISSUE TITLE
git push --force will cause an error in wadsworth, keeping it from redeploying ever again

### ISSUE THREAD

**Issue by Bios-Marcel** [Southclaws/wadsworth#4]
In order to work around the problem, it's easiest to just delete the cached git directory.

**Comment by Southclaws** [comment]
--force is evil on master branch! I don't really know a nice way to solve this. What's the exact error that is logged? It should work fine if you only --force in other branches then squash-merge to master as this doesn't rewrite the master commit history.

**Comment by Bios-Marcel** [comment]
Just the classic git error when you can't pull because someone pushed with force.

**Comment by Southclaws** [comment]
`--force-with-lease`

**Comment by Bios-Marcel** [comment]
God bless you

**Comment by Bios-Marcel** [comment]
Won't fix?!

**Comment by Southclaws** [comment]
I don't really know how, and I think it's best to just advise against force pushing to a mainline branch anyway, much simpler.
